### ISSUE TITLE
Student Showcase App

### ISSUE THREAD

**Issue by seanlowe** [seanlowe/milog#12]
Need to get crackin' on the application and abstract for the Spring 2019 Student Showcase.

**Abstract Approved By MacEvoy**
Mileage tracking is an important necessity for travelling employees that can be difficult to accomplish effectively. Popular mileage tracking apps record the distance travelled by recording a new trip when the user begins moving, and ending the trip once they have stopped. This can be a problem if multiple stops are made in a day, as it will save each trip separately, forcing the user to combine them manually. MiLog is a mileage tracking app that addresses these pitfalls and allows users to customize their logging experience and generate records regardless of whether they are an Android or iOS user. An accompanying website has many of the same functions in addition to more advanced reporting tools. This app lets users choose specifically when to begin or end a trip and features a pause function that lets the user temporarily suspend the trip in case of non-business errands or emergencies. The app keeps track of different vehicles as well as any tolls or parking fees accumulated. This helps individuals keep concise logs of their travels and simplifies itemizing deductions. Whether you are a independent contractor or a business owner, MiLog is the last mileage tracker you will ever need.

Please read and comment if you think it needs any changes. Has to stay 200 words or less. Right now it is sitting at a hefty 198 words.

**Comment by seanlowe** [comment]
Successful abstracts may answer some of the following questions:

    What question is the project attempting to answer?
    What was the motivation to work on this project?
    What background information does a reader need to fully understand the work?
    What points best summarize the research, demonstration, exhibit or performance?
    What results, conclusions, or final product will the presenter share?
    What are the larger implications or significance of the project?
    Who is the intended audience for the project?

**Comment by seanlowe** [comment]
**To complete the application, you will need:**
- Your completed abstract, reviewed by your faculty sponsor/mentor, and saved as a Microsoft Word (or similar program) document so that you can copy and paste the text into the application. 
 - The name, email address, and academic department of your faculty sponsor/mentor.
       --------> I assume MacEvoy is our faculty sponsor?

**Application Instructions for Group Projects**
 - If you complete the application on behalf of a group of presenters, you will also need each group member's complete first and last name and CMU email address.
 - Whichever student completes the application on behalf of a group will be considered the primary contact person for the presentation.
 - Only one application should be submitted for a group presentation, with the submitting student listing the other group members as co-presenters on the application.

**Comment by sonofmath** [comment]
Approved and agreed upon
