### ISSUE TITLE
Create User Profile Page - Flutter

### ISSUE THREAD

**Issue by sonofmath** [seanlowe/milog#15]
Create user profile page in flutter that allows user to view their details and update or delete their profile.

**Comment by seanlowe** [comment]
basic page finished

need to change a few widgets to input fields and tie into authentication so user can change email, password, or delete their account

**Comment by seanlowe** [comment]
Possible solution - webview that goes to the website where they can do account management

**Comment by seanlowe** [comment]
Page will remain as a mock-up for now .. can go back and add webviewer after showcase if desired.
