### ISSUE TITLE
Incorporate Vehicles

### ISSUE THREAD

**Issue by seanlowe** [seanlowe/milog#25]
Need to edit the database, trip and log functionalities to incorporate vehicles
Tasks include:
- create drop-down on new trip form with options like
    - Please Select Vehicle (option that drop-down starts on)
    - Create New Vehicle (if there are no created vehicles. selecting this will open up new vehicle screen)
    - Not Applicable (if you don't care? We can talk about this)
- create 'Vehicles' field in Database so that VehicleList page will actually work and have somewhere to pull data from + we have somewhere to store data to.

**Comment by seanlowe** [comment]
Database side + vehicleList finished

**Comment by seanlowe** [comment]
dropdown finished

**Comment by sonofmath** [comment]
Vehicles all working!
