### ISSUE TITLE
What Languages or Framework 

### ISSUE THREAD

**Issue by sonofmath** [seanlowe/milog#3]
React Native, Flutter, Android Studio, Xcode

**Comment by seanlowe** [comment]
I vote for separate Android Studio / XCode projects.

**Comment by rdunski** [comment]
Firebase for web, abstain for Android/iOS frameworks (I'm fine either way)

**Comment by sonofmath** [comment]
I feel we should separate them as well

**Comment by rdunski** [comment]
Decided on Firebase for Web, Android Studio for Android, and XCode for iOS.
