### ISSUE TITLE
Firebase Testing

### ISSUE THREAD

**Issue by rdunski** [seanlowe/milog#4]
Test database functionality, i.e. put one value into table and retrieve it later

**Comment by rdunski** [comment]
Working on Web database testing

**Comment by Blackbird002** [comment]
TODO: Android-
Test the defined classes with Firebase  getValue(Class<T> valueType) method. 
Need to see if it will correctly marshall the data contained in this snapshot into the Java classes: User, Trip, Vehicle.

[https://firebase.google.com/docs/reference/android/com/google/firebase/database/DataSnapshot](DataSnapshot)

**Comment by rdunski** [comment]
Established connection with firebase database by writing and reading data.

**Comment by rdunski** [comment]
Firebase functionality confirmed.
